package com.goodforallcode.jobExtractor.filter;

import com.goodforallcode.jobExtractor.filters.JobFilter;
import com.goodforallcode.jobExtractor.filters.deep.ApplicationEngineerFilter;
import com.goodforallcode.jobExtractor.filters.deep.always.StartupFilter;
import com.goodforallcode.jobExtractor.model.Job;
import com.goodforallcode.jobExtractor.util.TestUtil;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

public class ApplicationEngineerFilterTests {
    JobFilter filter =new ApplicationEngineerFilter();
    @Test
    void testIncludeNonDevTermsInDescription() {
        Job job=new Job("Application Engineer");
        job.setDescription("About the job How You Will Make An Impact The Application Engineer is responsible for developing custom specifications and build documentation to meet customer demands. This role will write specifications, design systems as well as fabricated components, and work with Operations to provide expertise and ensure build accuracy. This position will be home based at our Bowmansville, PA location. Some travel will be required – to customer locations in order to evaluate current builds. The Nuts and Bolts Write specifications to clearly define and document customer needs Create 3D layouts of overall builds for fit, form and function verification as well as customer approval Create and modify 3D models and AutoCAD drawings for assemblies, parts, schematics, etc. Responsible for compliance and regulation adherence Work with Design Engineers and Designers to ensure build documentation accuracy Assist Design Engineers with required engineering expertise to complete design activities May perform structural analysis for new and existing engineered components Layout, draw and reproduce illustrations for reference manuals and technical publications Support operations as required Work on multiple projects independently Required Credentials Looking for 7 years’ experience in similar field / role Associate degree required – Bachelor’s degree preferred Solidworks, AutoCAD or other 3D modeling software experience is required Aftermarket automotive system design experience – preferred Hydraulic and pneumatic system experience - preferred How We Make An Impact At Reading Truck, we have more than 65 years of industry leadership in the manufacture, distribution, and enhancement of work truck bodies. We continue to experience rapid growth through our expanding network of more than 20 locations across North America. Take the next step in your career and come get paid to play with trucks! Some of Our Total Rewards We offer big company perks with small company culture: Comprehensive benefits package including Medical, Dental, Vision and Life 401(k) Savings Plan with Company Match Tuition Reimbursement 10 paid holidays Generous Footwear, Eyewear, and Safety Equipment Discount Program Paid Training and Development Programs J.B. Poindexter & Co., Inc. provides equal employment opportunities to all employees and applicants for employment and prohibits discrimination and harassment of any type without regard to race, color, religion, age, sex, national origin, disability status, genetics, protected veteran status, sexual orientation, gender identity or expression, or any other characteristic protected by federal, state or local laws. This policy applies to all terms and conditions of employment, including recruiting, hiring, placement, promotion, termination, layoff, recall, transfer, leaves of absence, compensation and training. For other career opportunities, please visit our careers page https://www.readingtruck.com/about/careers Apply Now");
        assertFalse(filter.include(TestUtil.getDefaultPreferences(),job));
    }
    @Test
    void testExcludeNoApplicationInTitle() {
        Job job=new Job("NeoLoad Performance Engineer");
        job.setDescription("About the job How You Will Make An Impact The Application Engineer is responsible for developing custom specifications and build documentation to meet customer demands. This role will write specifications, design systems as well as fabricated components, and work with Operations to provide expertise and ensure build accuracy. This position will be home based at our Bowmansville, PA location. Some travel will be required – to customer locations in order to evaluate current builds. The Nuts and Bolts Write specifications to clearly define and document customer needs Create 3D layouts of overall builds for fit, form and function verification as well as customer approval Create and modify 3D models and AutoCAD drawings for assemblies, parts, schematics, etc. Responsible for compliance and regulation adherence Work with Design Engineers and Designers to ensure build documentation accuracy Assist Design Engineers with required engineering expertise to complete design activities May perform structural analysis for new and existing engineered components Layout, draw and reproduce illustrations for reference manuals and technical publications Support operations as required Work on multiple projects independently Required Credentials Looking for 7 years’ experience in similar field / role Associate degree required – Bachelor’s degree preferred Solidworks, AutoCAD or other 3D modeling software experience is required Aftermarket automotive system design experience – preferred Hydraulic and pneumatic system experience - preferred How We Make An Impact At Reading Truck, we have more than 65 years of industry leadership in the manufacture, distribution, and enhancement of work truck bodies. We continue to experience rapid growth through our expanding network of more than 20 locations across North America. Take the next step in your career and come get paid to play with trucks! Some of Our Total Rewards We offer big company perks with small company culture: Comprehensive benefits package including Medical, Dental, Vision and Life 401(k) Savings Plan with Company Match Tuition Reimbursement 10 paid holidays Generous Footwear, Eyewear, and Safety Equipment Discount Program Paid Training and Development Programs J.B. Poindexter & Co., Inc. provides equal employment opportunities to all employees and applicants for employment and prohibits discrimination and harassment of any type without regard to race, color, religion, age, sex, national origin, disability status, genetics, protected veteran status, sexual orientation, gender identity or expression, or any other characteristic protected by federal, state or local laws. This policy applies to all terms and conditions of employment, including recruiting, hiring, placement, promotion, termination, layoff, recall, transfer, leaves of absence, compensation and training. For other career opportunities, please visit our careers page https://www.readingtruck.com/about/careers Apply Now");
        assertTrue(filter.include(TestUtil.getDefaultPreferences(),job));
    }

}
